name: SR
favicon: null
layout_spectrum: 0.9557170928455889
typography_spectrum: 0.6714416840113699
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#513b16'
    - '#766042'
    - '#998772'
    - '#b5ab9a'
  brandStrength: 0.25
  lightness: 0.46056146803312004
  saturation: 0.8386200526729226
  rhythmicContrast: 0.008527329657226801
purpose: []
